language: python

python:
  - "3.5"

sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo apt-get update
  - sudo apt-get -y install liblua5.1-dev libffi-dev
  - pushd db
  - docker build -t faf-db .
  - docker run -d --name faf-db -e MYSQL_ROOT_PASSWORD=banana -p 3306:3306 faf-db
  - until docker exec -i faf-db ./healthcheck.sh 2>/dev/null; do sleep 1; done
  - docker exec -i faf-db mysql -uroot -pbanana -e "create database faf_test;"
  - docker exec -i faf-db mysql -uroot -pbanana faf < test-data.sql
  - popd
  - cp config.example.py config.py
  - python -m pip install coveralls

install:
  - docker build -t faf-api .

script:
  - docker run --name faf-api --link faf-db:db -e FAF_DB_PASSWORD=banana -e STEAM_API_KEY=$STEAM_API_KEY faf-api py.test --cov-report term-missing --cov=api
  - docker run --link faf-db:db -e FAF_DB_PASSWORD=banana faf-api pyflakes . || true

after_success:
  - docker run --link faf-db:db -e FAF_DB_PASSWORD=banana faf-api coveralls
  - docker cp faf-api:/code/.coverage .coverage
  - sed -i.bak s#/code/#$(pwd)/#g .coverage
  - coveralls
